services:
  # django:
  #   image: django-crm
  #   container_name: django-crm
  #   build:
  #     context: .
  #     dockerfile: ./docker/django/Dockerfile
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #   command: python3 manage.py runserver 0.0.0.0:8000
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true
  #   volumes:
  #     - ./project/:/app/
  #   networks:
  #     - django-crm-network

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: crm_postgres
    container_name: crm_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - django-crm-network

networks:
  django-crm-network:
    name: django-crm-network
